### ISSUE TITLE
Fix test script for Android

### ISSUE THREAD

**Issue by kjozwiak** [brave/qa-resources#183]
Selecting `Android` via `python3 brave_testrun_generator.py` produces the following error:

```
Generating test runs for 
Traceback (most recent call last):
  File "brave_testrun_generator.py", line 933, in <module>
    android_testruns(androidkey)
  File "brave_testrun_generator.py", line 590, in android_testruns
    milestone=laptop_milestone[milestonever],
KeyError: ''
```

**Comment by srirambv** [comment]
This is due to change in process. I'll try fixing it soon
